[manifest]
version = "0.0.1"
dump_lua = true
priority = 1000

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "DARK_EDITION = {0,0,0,1},"
position = "after"
payload = """
OMEGABLACK = HEX("000000"),
OMEGARED = HEX("ff0000"),
OMEGAWHITE = HEX("ffffff"),
NIGHTMARE_BLUE = HEX("0000ff"),
NIGHTMARE_PURPLE = HEX("800080"),
PASTEL_YELLOW = HEX("FFFC75"),
PINK = HEX("FFAAD9"),
ISO_LIGHT_PURPLE = HEX("df9aff"),
ISO_DARK_PURPLE = HEX("cf69ff"),
ISO_CRIMSON = HEX("870000"),
ISO_APOC = HEX("ffa852"),
ISO_INDEX_BLUE = HEX("86bada"),
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "dark_edition = G.C.DARK_EDITION,"
position = "after"
payload = """
fizz_omegablack = G.C.OMEGABLACK,
fizz_omegared = G.C.OMEGARED,
fizz_omegawhite = G.C.OMEGAWHITE,
fizz_nightmare_blue = G.C.NIGHTMARE_BLUE,
fizz_nightmare_purple = G.C.NIGHTMARE_PURPLE,
pastel_yellow = G.C.PASTEL_YELLOW,
pink = G.C.PINK,
fizz_light_purple = G.C.ISO_LIGHT_PURPLE,
fizz_dark_purple = G.C.ISO_DARK_PURPLE,
fizz_crimson = G.C.ISO_CRIMSON,
fizz_apoc = G.C.ISO_APOC,
fizz_index_blue = G.C.ISO_INDEX_BLUE,
"""
match_indent = true